[package]
name = "toyoterm-pty"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tracing.workspace = true

[target.'cfg(unix)'.dependencies]
portable-pty.workspace = true

[target.'cfg(windows)'.dependencies]
conpty-oxide = { version = "0.1.2", features = ["tracing"] }

[dev-dependencies]
toyoterm-terminal.workspace = true
