[package]
name = "toyoterm-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
toyoterm-api.workspace = true
toyoterm-config.workspace = true
toyoterm-ipc.workspace = true
toyoterm-mux.workspace = true
toyoterm-pty.workspace = true
toyoterm-render.workspace = true
toyoterm-script.workspace = true
toyoterm-terminal.workspace = true
arboard.workspace = true
pollster.workspace = true
sys-locale.workspace = true
tracing.workspace = true
winit.workspace = true
